### ISSUE TITLE
Cannot install via NodeJS

### ISSUE THREAD

**Issue by CZechBoY** [danielgtaylor/aglio#139]
Hi,
here is npm-debug.log:
http://ulozto.net/xQQ5m9jJ/npm-debug-log

**Comment by pksunkara** [comment]
Can you paste it here itself? Thanks.

**Comment by kylef** [comment]
Appears protagonist's `node-gyp rebuild` failed, here's the part of log related:

```
31803 verbose about to build C:\Users\Adam\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist
31804 info build C:\Users\Adam\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist
31805 info linkStuff protagonist@0.20.1
31806 silly linkStuff protagonist@0.20.1 has C:\Users\Adam\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules as its parent node_modules
31807 silly linkStuff protagonist@0.20.1 is part of a global install
31808 silly linkStuff protagonist@0.20.1 is installed into a global node_modules
31809 verbose linkBins protagonist@0.20.1
31810 verbose linkMans protagonist@0.20.1
31811 verbose rebuildBundles protagonist@0.20.1
31812 verbose rebuildBundles [ 'nan' ]
31813 info install protagonist@0.20.1
31814 verbose unsafe-perm in lifecycle true
31815 verbose unlock done using C:\Users\Adam\AppData\Roaming\npm-cache\_locks\aglio-theme-olio-f988bf6db9500529.lock for C:\Users\Adam\AppData\Roaming\npm\node_modules\aglio\node_modules\aglio-theme-olio
31816 info protagonist@0.20.1 Failed to exec install script
31817 verbose unlock done using C:\Users\Adam\AppData\Roaming\npm-cache\_locks\protagonist-9ded13660b9832a0.lock for C:\Users\Adam\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist
31818 verbose about to build C:\Users\Adam\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter
31819 verbose unlock done using C:\Users\Adam\AppData\Roaming\npm-cache\_locks\drafter-f51f412e04289eb8.lock for C:\Users\Adam\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter
31820 verbose about to build C:\Users\Adam\AppData\Roaming\npm\node_modules\aglio
31821 verbose unlock done using C:\Users\Adam\AppData\Roaming\npm-cache\_locks\aglio-d6fdfbcc59558057.lock for C:\Users\Adam\AppData\Roaming\npm\node_modules\aglio
31822 verbose stack Error: protagonist@0.20.1 install: `node-gyp rebuild`
31822 verbose stack Exit status 1
31822 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
31822 verbose stack     at EventEmitter.emit (events.js:110:17)
31822 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
31822 verbose stack     at ChildProcess.emit (events.js:110:17)
31822 verbose stack     at maybeClose (child_process.js:1015:16)
31822 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
31823 verbose pkgid protagonist@0.20.1
31824 verbose cwd C:\Users\Adam
31825 error Windows_NT 6.3.9600
31826 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "aglio"
31827 error node v0.12.7
31828 error npm  v2.11.3
31829 error code ELIFECYCLE
31830 error protagonist@0.20.1 install: `node-gyp rebuild`
31830 error Exit status 1
31831 error Failed at the protagonist@0.20.1 install script 'node-gyp rebuild'.
31831 error This is most likely a problem with the protagonist package,
31831 error not with npm itself.
31831 error Tell the author that this fails on your system:
31831 error     node-gyp rebuild
31831 error You can get their info via:
31831 error     npm owner ls protagonist
31831 error There is likely additional logging output above.
31832 verbose exit [ 1, true ]
```

**Comment by pksunkara** [comment]
Related to apiaryio/protagonist#35?

**Comment by kylef** [comment]
That's unrelated, apiaryio/protagonist#35 is regarding a crash when running on windows. This issue is a failure to install protagonist.

**Comment by pksunkara** [comment]
@kylef Ah missed that. Thanks.

@CZechBoY Can you make sure your python version is 2.6?

**Comment by CZechBoY** [comment]
@pksunkara my python version is 3.4

**Comment by pksunkara** [comment]
Can you try it once with 2.7? Thanks.

**Comment by dredav** [comment]
It works on my side with python 2.7! Thanks
`sudo npm install -g aglio --python=python2.7`

**Comment by CZechBoY** [comment]
Just tried on Win8 with the --python argument:

```
C:\Users\czech_000\Desktop>npm install -g aglio --python=python2.7
npm WARN optional dep failed, continuing fsevents@1.0.6
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.1
0.32","npm":"1.4.28"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.1
0.32","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":
"0.10.32","npm":"1.4.28"})
/
> aglio-theme-olio@1.6.2 postinstall C:\Users\czech_000\AppData\Roaming\npm\node
_modules\aglio\node_modules\aglio-theme-olio
> node scripts/setup-cache.js

|
> protagonist@1.2.5 install C:\Users\czech_000\AppData\Roaming\npm\node_modules\
aglio\node_modules\protagonist
> node-gyp rebuild


C:\Users\czech_000\AppData\Roaming\npm\node_modules\aglio\node_modules\protagoni
st>node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_m
odules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python2.7", you can set the
PYTHON env variable.
gyp ERR! stack     at failNoPython (D:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\czech_000\AppData\Roaming\npm\node_modules\aglio\node_modu
les\protagonist
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! protagonist@1.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protagonist@1.2.5 install script.
npm ERR! This is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "D:\\Program Files\\nodejs\\\\node.exe" "D:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "aglio" "--python=python
2.7"
npm ERR! cwd C:\Users\czech_000\Desktop
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by CZechBoY** [comment]
Anybody?
@danielgtaylor @pksunkara

**Comment by pksunkara** [comment]
@CZechBoY It might be an issue with your node version. Can you upgrade to node 0.12 and see what happens?
