### ISSUE TITLE
Error: Module version mismatch. Expected 46, got 47

### ISSUE THREAD

**Issue by esseti** [danielgtaylor/aglio#244]
Just had this when running aglio
```
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/stefano/.node_modules/lib/node_modules/aglio/lib/main.js:9:17)
    at Object.<anonymous> (/Users/stefano/.node_modules/lib/node_modules/aglio/lib/main.js:220:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

```

do I've to use a version of node older than 4.4.0?

**Comment by kylef** [comment]
This sounds like you may have install Aglio (and protagonist) with a different version of node than you are currently running.

If this is the case, the following should solve the problem:

```shell
$ npm uninstall -g aglio
$ npm install -g aglio
```

**Comment by esseti** [comment]
I actually installed last version of node (using nvm) and of npm and aglio and it works.

**Comment by Harsh-Pandey** [comment]
I am facing similar issue as of @esseti . Can you please elaborate a little on how did you resolve the issue.
My error goes as follows:
Error: Module version mismatch. Expected 46, got 51.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/node-pi-lesson-1/node_modules/wiring-pi/lib/exports.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

**Comment by kylef** [comment]
@Harsh-Pandey This problem is when Protagonist (a dependency of Agilo) was installed with a different version of node. Completely reinstalling Aglio should solve the problem as mentioned [in my previous comment](https://github.com/danielgtaylor/aglio/issues/244#issuecomment-197325224).
