### ISSUE TITLE
npm ERR! aglio-theme-olio@1.6.3 postinstall: `node scripts/setup-cache.js`

### ISSUE THREAD

**Issue by kadishmal** [danielgtaylor/aglio#260]
It fails with both `aglio` `2.2.0` and `2.2.1`. This happens when the `aglio-theme-olio` has been upgraded to `1.6.3`.

```bash
npm ERR! Linux 4.0.9-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "aglio"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! aglio-theme-olio@1.6.3 postinstall: `node scripts/setup-cache.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aglio-theme-olio@1.6.3 postinstall script 'node scripts/setup-cache.js'.
npm ERR! This is most likely a problem with the aglio-theme-olio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/setup-cache.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aglio-theme-olio
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls aglio-theme-olio
npm ERR! There is likely additional logging output above.
npm info preuninstall aglio-theme-olio@1.6.3
npm info uninstall aglio-theme-olio@1.6.3
npm info postuninstall aglio-theme-olio@1.6.3
npm info preuninstall aglio@2.2.0
npm info uninstall aglio@2.2.0
npm info postuninstall aglio@2.2.0

npm ERR! Please include the following file with any support request:
npm ERR!     /webapp/npm-debug.log
```

`npm-debug.log` says:

```
20393 info aglio-theme-olio@1.6.3 Failed to exec postinstall script
20394 verbose unsafe-perm in lifecycle false
20395 verbose unlock done using /root/.npm/_locks/aglio-theme-olio-a96b3bff19dc352e.lock for /webapp/node_modules/aglio/node_modules/aglio-theme-olio
20396 info postinstall protagonist@1.3.3
20397 verbose unlock done using /root/.npm/_locks/protagonist-cb036dc5e581a117.lock for /webapp/node_modules/aglio/node_modules/protagonist
20398 verbose about to build /webapp/node_modules/aglio
20399 verbose unlock done using /root/.npm/_locks/aglio-a3c3fc6176a22ff3.lock for /webapp/node_modules/aglio
20400 verbose stack Error: aglio-theme-olio@1.6.3 postinstall: `node scripts/setup-cache.js`
20400 verbose stack Exit status 1
20400 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
20400 verbose stack     at emitTwo (events.js:87:13)
20400 verbose stack     at EventEmitter.emit (events.js:172:7)
20400 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
20400 verbose stack     at emitTwo (events.js:87:13)
20400 verbose stack     at ChildProcess.emit (events.js:172:7)
20400 verbose stack     at maybeClose (internal/child_process.js:827:16)
20400 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
20401 verbose pkgid aglio-theme-olio@1.6.3
20402 verbose cwd /webapp
20403 error Linux 4.0.9-boot2docker
20404 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "aglio"
20405 error node v4.4.3
20406 error npm  v2.15.1
20407 error code ELIFECYCLE
20408 error aglio-theme-olio@1.6.3 postinstall: `node scripts/setup-cache.js`
20408 error Exit status 1
20409 error Failed at the aglio-theme-olio@1.6.3 postinstall script 'node scripts/setup-cache.js'.
20409 error This is most likely a problem with the aglio-theme-olio package,
20409 error not with npm itself.
20409 error Tell the author that this fails on your system:
20409 error     node scripts/setup-cache.js
20409 error You can get information on how to open an issue for this project with:
20409 error     npm bugs aglio-theme-olio
20409 error Or if that isn't available, you can get their info via:
20409 error
20409 error     npm owner ls aglio-theme-olio
20409 error There is likely additional logging output above.
20410 verbose exit [ 1, true ]
```

**Comment by danielgtaylor** [comment]
@kadishmal if you manually install the 1.6.2 version does that work? Does 1.6.3 consistently fail for you? Any other info you can give me? It is installing okay for me. Anybody else having this issue?

**Comment by justinmchase** [comment]
I am also encountering this but only on my docker container. It works fine on osx.

**Comment by justinmchase** [comment]
I think that the postinstall should actually be:

```
"postinstall": "bash ./scripts/setup-cache.js"
```

Relative path to scripts and bash instead of node, since your script file has a shebang it should work fine.
```
#!/usr/bin/env node
```

**Comment by awishformore** [comment]
I have the same issue on Ubuntu 16.10.

**Comment by emilsedgh** [comment]
This happens to me when Gitlab wants to run our CI.

Since it's inside Gitlab I don't have access to the machine so I can hardly debug it.

However, it would be very helpful if you log the error in here:
https://github.com/danielgtaylor/aglio/blob/olio-theme/scripts/setup-cache.js#L9

In the released version, the `../lib/main` is supposed to be always there.
I think there is another exception happening there that we cannot see because the error is ignored.

Not sure how I can debug this any other way as I don't have shell access to the machine that has this problem (Gitlab.com runners)
