### ISSUE TITLE
Error: Unknown language: "shell"

### ISSUE THREAD

**Issue by edwardaa** [danielgtaylor/aglio#296]
```
Error: Unknown language: "shell"
    at Object.highlight (/usr/lib/node_modules/aglio/node_modules/aglio-theme-olio/node_modules/highlight.js/lib/highlight.js:443:13)
    at /usr/lib/node_modules/aglio/node_modules/aglio-theme-olio/lib/main.js:92:23
    at Object.highlight (/usr/lib/node_modules/aglio/node_modules/aglio-theme-olio/lib/main.js:94:7)
    at Object.default_rules.fence (/usr/lib/node_modules/aglio/node_modules/aglio-theme-olio/node_modules/markdown-it/lib/renderer.js:43:27)
    at Renderer.render (/usr/lib/node_modules/aglio/node_modules/aglio-theme-olio/node_modules/markdown-it/lib/renderer.js:292:38)
    at MarkdownIt.render (/usr/lib/node_modules/aglio/node_modules/aglio-theme-olio/node_modules/markdown-it/lib/index.js:513:24)
    at decorate (/usr/lib/node_modules/aglio/node_modules/aglio-theme-olio/lib/main.js:404:32)
    at Object.exports.render (/usr/lib/node_modules/aglio/node_modules/aglio-theme-olio/lib/main.js:646:5)
    at /usr/lib/node_modules/aglio/lib/main.js:133:20

```

**Comment by jackbentley** [comment]
I'm assuming this is from a code block with the language set to `shell`? Something like this?

```markdown
   ```shell
      ... code ...
   ``
```

Can you post an example failing api-blueprint? Alternatively, changing the code block language to `bash` (etc) might work?
