### ISSUE TITLE
Master version does not run

### ISSUE THREAD

**Issue by why-el** [danielgtaylor/aglio#306]
I installed using: 

`npm install -g danielgtaylor/aglio`

Then, when running `aglio`, I get: 

```
11:34 $ aglio
module.js:341
    throw err;
    ^

Error: Cannot find module '../lib/bin'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/aglio/bin/aglio.js:5:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

**Comment by kylef** [comment]
@why-el you would need to run the prepublish commands which compile the source code.

```
$ git clone https://github.com/danielgtaylor/aglio
$ cd aglio
$ npm install
$ npm prepublish
$ npm link
```

**Comment by why-el** [comment]
I see, not too familiar with npm. :) Thank you.
