### ISSUE TITLE
Error: Module did not self-register.

### ISSUE THREAD

**Issue by shepparddigital** [danielgtaylor/aglio#311]
I've had Aglio installed on Centos 7 for a while now, and it's been working great. However after a 'yum update' last week, Aglio no longer works and simply throws up the following error;

`
aglio --theme-full-width -i docs2.apib -o docs2.html
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/aglio/lib/main.js:9:17)
    at Object.<anonymous> (/usr/lib/node_modules/aglio/lib/main.js:220:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
`

I've attempted to uninstall both aglio and nodejs/npm and re-install them all, but it didn't resolve the issue.

**Comment by StevenRichards** [comment]
Same issue on Ubuntu 14.04, NPM 4.0.5, Node 6.9.2. Have tried npm rebuild; removing node_modules and running npm install; re-installing/rebuilding aglio.

**Comment by mstaack** [comment]
same for me!
```
└> npm -v
5.4.0

└> node -v
v8.4.0
```
