### ISSUE TITLE
TypeError: token.attrGet is not a function

### ISSUE THREAD

**Issue by kadishmal** [danielgtaylor/aglio#319]
```bash
   "TypeError: token.attrGet is not a function",
    "    at /home1/user/61916c91a4e81be8/node_modules/markdown-it-anchor/index.js:79:24",
    "    at Array.forEach (native)",
    "    at Array.<anonymous> (/home1/user/61916c91a4e81be8/node_modules/markdown-it-anchor/index.js:71:8)",
    "    at Core.process (/home1/user/61916c91a4e81be8/node_modules/markdown-it/lib/parser_core.js:51:13)",
    "    at MarkdownIt.parse (/home1/user/61916c91a4e81be8/node_modules/markdown-it/lib/index.js:493:13)",
    "    at MarkdownIt.render (/home1/user/61916c91a4e81be8/node_modules/markdown-it/lib/index.js:513:36)",
    "    at decorate (/home1/user/61916c91a4e81be8/node_modules/aglio-theme-olio/lib/main.js:422:44)",
    "    at Object.exports.render (/home1/user/61916c91a4e81be8/node_modules/aglio-theme-olio/lib/main.js:646:5)",
    "    at /home1/user/61916c91a4e81be8/node_modules/aglio/lib/main.js:133:20"
```

The above error occurs due to the fact that `markdown-it-anchor` has released `v2.7.0` which introduces some breaking changes. I am not sure if it was `v2.6.0` but `v2.5.0` I installed last time works fine.

The following works fine:

```
`-- grunt-aglio@0.4.1
  `-- aglio@2.2.1
    `-- aglio-theme-olio@1.6.3
      `-- markdown-it-anchor@2.5.0
```

This new version fails.

```
└─┬ grunt-aglio@0.4.1
  └─┬ aglio@2.2.1
    └─┬ aglio-theme-olio@1.6.3
      └── markdown-it-anchor@2.7.0
```

Some clever people here at `aglio` didn't care enough to set the exact version requirement in its [package.json](https://github.com/danielgtaylor/aglio/blob/olio-theme/package.json#L42).

Please, always use the exact version.

**Comment by fricklerhandwerk** [comment]
This can be addressed by bumping to a current `markdown-it`, see #320.
