### ISSUE TITLE
Can't install aglio

### ISSUE THREAD

**Issue by mleroyy** [danielgtaylor/aglio#345]
Hi ! I have troubles installing agile with my configuration. I don't really know what to do. Can you help ?

```
➜  ~ sudo npm install -g aglio
Password:
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/aglio -> /usr/local/lib/node_modules/aglio/bin/aglio.js

> fsevents@1.1.3 install /usr/local/lib/node_modules/aglio/node_modules/fsevents
> node install

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
path.js:1180
          cwd = process.cwd();
                        ^

Error: EACCES: permission denied, uv_cwd
    at Object.resolve (path.js:1180:25)
    at startup (bootstrap_node.js:172:32)
    at bootstrap_node.js:613:3

> protagonist@1.6.8 install /usr/local/lib/node_modules/aglio/node_modules/protagonist
> node-gyp rebuild

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
sh: node-gyp: command not found

> aglio-theme-olio@1.6.3 postinstall /usr/local/lib/node_modules/aglio/node_modules/aglio-theme-olio
> node scripts/setup-cache.js

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
path.js:1180
          cwd = process.cwd();
                        ^

Error: EACCES: permission denied, uv_cwd
    at Object.resolve (path.js:1180:25)
    at startup (bootstrap_node.js:172:32)
    at bootstrap_node.js:613:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/aglio/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: protagonist@1.6.8 (node_modules/aglio/node_modules/protagonist):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: protagonist@1.6.8 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aglio-theme-olio@1.6.3 postinstall: `node scripts/setup-cache.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aglio-theme-olio@1.6.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mathieuleroy/.npm/_logs/2017-11-24T01_21_12_402Z-debug.log
```

**Comment by thomasedwards** [comment]
What are the permissions of your `node_modules` directory?

Run:

```
ls -l /usr/local/lib
```

Then look for something like this:

```
drwxr-xr-x   8 myname  admin  272 25 Jan 12:30 node_modules
```

The first part of the row are the permissions, and the `myname` and `admin` are the owners (user and group). Let us know what they are and we can try and help from there.
