### ISSUE TITLE
TypeError: unrecognized option 'type' , node v11.9.0

### ISSUE THREAD

**Issue by tripper54** [danielgtaylor/aglio#366]
using node v11.9.0, I get a Type error:

```
TypeError: unrecognized option 'type', expected: 'requireBlueprintName', 'generateSourceMap'
    at Object.exports.render (/site/node_modules/aglio/lib/main.js:99:20)
    at render (/site/node_modules/aglio/lib/main.js:147:22)
    at /site/node_modules/aglio/lib/main.js:171:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
```

node v10.15.3 works fine.

**Comment by miguel-rodriguez-cimino** [comment]
Node v10.15.3 throws the same error

**Comment by Gasol** [comment]
Take a look at https://github.com/danielgtaylor/aglio/issues/362#issuecomment-499086348

**Comment by stevebaxter** [comment]
This is happening for me with Node 12.18.3

**Comment by D1360-64RC14** [comment]
Same on node v14.17.0

```
user@host:/...$ aglio -i docs/docs.apib -s
Server started on http://127.0.0.1:3000/
Rendering docs/docs.apib
/.../node_modules/aglio/lib/main.js:99
    return drafter.parse(filteredInput, {
                   ^

TypeError: unrecognized option 'type', expected: 'requireBlueprintName', 'generateMessageBody', 'generateMessageBodySchema', 'generateSourceMap'
    at Object.exports.render (/.../node_modules/aglio/lib/main.js:99:20)
    at /.../node_modules/aglio/lib/bin.js:126:24
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)
```

**Using Aglio from @Gasol worked pretty well.**

```
yarn add https://github.com/Gasol/aglio.git
```
