### ISSUE TITLE
Can't install aglio for wsl2

### ISSUE THREAD

**Issue by toknT** [danielgtaylor/aglio#375]
```sh
$ uname -a
Linux LAPTOP-0GMIMIDK 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$  node -v                                                                                                                                                                                                  
v14.18.1
$ node -v                                                                                                                                                                                                  
v14.18.1
```

```sh
npm install -g aglio
/home/toknsit/.cache/node-gyp/14.18.1/include/node/v8.h:2822:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
 2822 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
      |                                            ^~~~~~~~
/home/toknsit/.cache/node-gyp/14.18.1/include/node/v8.h:2822:44: note:   candidate expects 1 argument, 0 provided
make: *** [protagonist.target.mk:165: Release/obj.target/protagonist/src/annotation.o] Error 1
make: Leaving directory '/home/toknsit/.npm-global/lib/node_modules/aglio/node_modules/protagonist/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 5.10.60.1-microsoft-standard-WSL2
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/toknsit/.npm-global/lib/node_modules/aglio/node_modules/protagonist
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

note: https://github.com/danielgtaylor/aglio/issues/352#issuecomment-387715105  configure npm to use a different directory still return error

**Comment by toknT** [comment]
sorry it print err in console but successfully installed  aglio to my wsl🙏
