### ISSUE TITLE
file not found error

### ISSUE THREAD

**Issue by vikhyath** [danielgtaylor/aglio#85]
Thanks for aglio. I used it a while back it worked fine but when I tried it out today after a fresh "npm install", it seems to have problems.

$> aglio -i example.md -o test.html

fs.js:438
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'example-include.md'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at includeReplace (/root/.nvm/v0.10.31/lib/node_modules/aglio/lib/main.js:43:16)
    at String.replace (native)
    at includeDirective (/root/.nvm/v0.10.31/lib/node_modules/aglio/lib/main.js:49:18)
    at Object.exports.render (/root/.nvm/v0.10.31/lib/node_modules/aglio/lib/main.js:116:13)
    at render (/root/.nvm/v0.10.31/lib/node_modules/aglio/lib/main.js:161:22)
    at /root/.nvm/v0.10.31/lib/node_modules/aglio/lib/main.js:185:16
    at fs.js:271:14
    at /root/.nvm/v0.10.31/lib/node_modules/aglio/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:104:5

Am I doing something incorrect here?

**Comment by 3mind-** [comment]
@vikhyath do you have example-include.md in the same directory/folder as the example.md ?

**Comment by danielgtaylor** [comment]
@vikhyath the example file that ships with Aglio has been updated to include another file as mentioned above. If you want to use the example, you'll need to copy both `example.md` and `example-include.md` into the same folder. Please let me know if you have any other questions.
