### ISSUE TITLE
Aglio does compile on official Nodejs image

### ISSUE THREAD

**Issue by davidonlaptop** [danielgtaylor/aglio#95]
# Steps to reproduce
```
docker run --rm -ti node:0.12.1 bash
root@80b09846445d:/# npm install -g aglio
```

## Detailed error message
```
protagonist.target.mk:124: recipe for target 'Release/obj.target/protagonist/src/annotation.o' failed
make: *** [Release/obj.target/protagonist/src/annotation.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/aglio/node_modules/protagonist/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.18.5-tinycore64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/aglio/node_modules/protagonist
gyp ERR! node -v v0.12.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.18.5-tinycore64
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "aglio"
npm ERR! node v0.12.1
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE

npm ERR! protagonist@0.17.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the protagonist@0.17.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

**Comment by danielgtaylor** [comment]
Try using `aglio@experimental` for node 0.12 support. A new release is
coming soon with full support.

**Comment by davidonlaptop** [comment]
Thanks it works with the experimental flag.

FYI. I've published a [public Aglio image](https://registry.hub.docker.com/u/davidonlaptop/aglio/) on the Docker registry. For now, I am using a shrinkwrapped version of Aglio 1.16 (master branch). I've created an 'aglio-experimental' branch to confirm that it works.

**Comment by danielgtaylor** [comment]
@davidonlaptop please have a try today. I've just released 1.18.0 that includes support for Node.js 0.12 and io.js 1.x. Let me know if you run into any other issues.

**Comment by davidonlaptop** [comment]
Great, it works!

I'll publish an updated Docker image soon.

**Comment by davidonlaptop** [comment]
Building... https://registry.hub.docker.com/u/davidonlaptop/aglio/builds_history/168098/

**Comment by davidonlaptop** [comment]
Done. thanks @danielgtaylor
