### ISSUE TITLE
Errors on install

### ISSUE THREAD

**Issue by joshhornby** [danielgtaylor/aglio#97]
When running the command 

```sudo npm install -g aglio```

The following happens:

```
> fsevents@0.3.5 install /usr/local/lib/node_modules/aglio/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished
 
> ws@0.5.0 install /usr/local/lib/node_modules/aglio/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> protagonist@0.17.2 install /usr/local/lib/node_modules/aglio/node_modules/protagonist
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/CBlueprint.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/CBlueprintSourcemap.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/CSourceAnnotation.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/HTTP.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/Section.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/Serialize.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/SerializeJSON.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/SerializeYAML.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/Signature.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/snowcrash.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/csnowcrash.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/UriTemplateParser.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/posix/RegexMatch.o
  LIBTOOL-STATIC Release/snowcrash.a
  CXX(target) Release/obj.target/libmarkdownparser/snowcrash/ext/markdown-parser/src/ByteBuffer.o
  CXX(target) Release/obj.target/libmarkdownparser/snowcrash/ext/markdown-parser/src/MarkdownNode.o
  CXX(target) Release/obj.target/libmarkdownparser/snowcrash/ext/markdown-parser/src/MarkdownParser.o
  LIBTOOL-STATIC Release/markdownparser.a
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/autolink.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/buffer.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/markdown.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/src_map.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/stack.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/houdini_href_e.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/houdini_html_e.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/html.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/html_smartypants.o
  LIBTOOL-STATIC Release/sundown.a
  CXX(target) Release/obj.target/protagonist/src/annotation.o
In file included from ../src/annotation.cc:1:
../src/protagonist.h:13:36: error: expected class name
    class Blueprint : public node::ObjectWrap {
                                   ^
../src/protagonist.h:28:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/joshuahornby/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/annotation.cc:1:
../src/protagonist.h:35:36: error: expected class name
    class Sourcemap : public node::ObjectWrap {
                                   ^
../src/protagonist.h:50:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/joshuahornby/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/annotation.cc:1:
../src/protagonist.h:57:43: error: expected class name
    class SourceAnnotation : public node::ObjectWrap {
                                          ^
../src/protagonist.h:69:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/joshuahornby/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/annotation.cc:1:
../src/protagonist.h:76:33: error: expected class name
    class Result : public node::ObjectWrap {
                                ^
../src/protagonist.h:92:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/joshuahornby/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/annotation.cc:1:
../src/protagonist.h:99:46: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    extern v8::Handle<v8::Value> Parse(const v8::Arguments& args);
                                             ^~~~~~~~~~~~~
                                             v8::internal::Arguments
/Users/joshuahornby/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/annotation.cc:19:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/joshuahornby/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/annotation.cc:21:55: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'v8::Handle<v8::Value> (const v8::internal::Arguments &)'
    Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                      ^~~
/Users/joshuahornby/.node-gyp/0.12.0/deps/v8/include/v8.h:3456:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate,
               ^
../src/annotation.cc:23:29: error: no member named 'NewSymbol' in 'v8::String'
    t->SetClassName(String::NewSymbol("SourceAnnotation"));
                    ~~~~~~~~^
../src/annotation.cc:25:41: error: 'New' is a private member of 'v8::PersistentBase<v8::Function>'
    constructor = Persistent<Function>::New(t->GetFunction());
                                        ^
/Users/joshuahornby/.node-gyp/0.12.0/deps/v8/include/v8.h:572:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../src/annotation.cc:25:61: error: too few arguments to function call, expected 2, have 1
    constructor = Persistent<Function>::New(t->GetFunction());
                  ~~~~~~~~~~~~~~~~~~~~~~~~~                 ^
/Users/joshuahornby/.node-gyp/0.12.0/deps/v8/include/v8.h:572:3: note: 'New' declared here
  V8_INLINE static T* New(Isolate* isolate, T* that);
  ^
/Users/joshuahornby/.node-gyp/0.12.0/deps/v8/include/v8config.h:289:20: note: expanded from macro 'V8_INLINE'
# define V8_INLINE inline __attribute__((always_inline))
                   ^
../src/annotation.cc:26:26: error: no member named 'NewSymbol' in 'v8::String'
    exports->Set(String::NewSymbol("SourceAnnotation"), constructor);
                 ~~~~~~~~^
../src/annotation.cc:29:43: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> SourceAnnotation::New(const Arguments& args)
                                          ^~~~~~~~~
                                          v8::internal::Arguments
/Users/joshuahornby/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/annotation.cc:31:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/joshuahornby/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/annotation.cc:33:17: error: no member named 'Wrap' in 'protagonist::SourceAnnotation'
    annotation->Wrap(args.This());
    ~~~~~~~~~~  ^
../src/annotation.cc:33:26: error: member access into incomplete type 'const v8::internal::Arguments'
    annotation->Wrap(args.This());
                         ^
/Users/joshuahornby/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/protagonist/src/annotation.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/aglio/node_modules/protagonist
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

> ws@0.4.31 install /usr/local/lib/node_modules/aglio/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "aglio"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! protagonist@0.17.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the protagonist@0.17.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above
```

**Comment by danielgtaylor** [comment]
@joshhornby one of our dependencies did not support Node.js 0.12 or io.js 1.x, but I have just pushed a new release to use an updated dependency. Please try it again.

**Comment by ChrisZieba** [comment]
I'm  having a similar issue after running `npm install`

```
npm http 304 https://registry.npmjs.org/highlight.js
npm ERR! Error: No compatible version found: coffee-script@'^1.8.0'
npm ERR! Valid install targets:
npm ERR! ["0.7.0","0.7.1","0.7.2","0.9.0","0.9.1","0.9.2","0.9.3","0.9.4","0.9.5","0.9.6","1.0.0","1.0.1","1.1.0","1.1.1","1.1.2","1.1.3","1.2.0","1.3.0","1.3.1","1.3.2","1.3.3","1.4.0","1.5.0","1.6.0","1.6.1","1.6.2","1.6.3","1.7.0","1.7.1","1.8.0","1.9.0","1.9.1"]
npm ERR!     at installTargetsError (/usr/local/Cellar/node/0.8.14/lib/node_modules/npm/lib/cache.js:709:10)
npm ERR!     at /usr/local/Cellar/node/0.8.14/lib/node_modules/npm/lib/cache.js:631:10
npm ERR!     at saved (/usr/local/Cellar/node/0.8.14/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/zieba/Documents/Projects/LemonStand/api-docs
npm ERR! node -v v0.10.7
npm ERR! npm -v 1.2.21
```

package.json:

```
{
  "name": "api-docs",
  "description": "test app",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "express": "4.x",
    "aglio": "1.x"
  }
}
```

**Comment by joshhornby** [comment]
Seems to have been fixed for me :+1:
